WebApplication11/Controllers/CompanySetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication11.Models;

namespace WebApplication11.Controllers
{
    public class CompanySetsController : Controller
    {
        private Model11 db = new Model11();

        // GET: CompanySets
        [Authorize(Roles = "Admin, ReadUser")]
        public ActionResult Index()
        {
            return View(db.CompanySet.ToList());
        }

        public ActionResult Upload()
        {
            var file = Request.Files["Filedata"];
            string savePath = Server.MapPath(@"~\UploadFiles\CompanySets\" + file.FileName);
            file.SaveAs(savePath);

            return Content(Url.Content(@"~\UploadFiles\CompanySets\" + file.FileName));
        }

        public JsonResult IsName(string Name)
        {
            return Json(!db.CompanySet.Any(x => x.Name == Name),
                                                 JsonRequestBehavior.AllowGet);
        }

        // GET: CompanySets/Details/5
        [Authorize(Roles = "Admin, ReadUser")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanySet companySet = db.CompanySet.Find(id);
            if (companySet == null)
            {
                return HttpNotFound();
            }
            return View(companySet);
        }


       


        // GET: CompanySets/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CompanySets/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyId,Name,address,inn,numnalog,kpp,rs,Bank,ks,bic,ogrn,numgos,okved,oktmo,okato,tel,mailaddress,gendir")] CompanySet companySet, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                db.CompanySet.Add(companySet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(companySet);
        }

        //    //Добавляем файл
        //{
        //    if (file == null)
        //    {
        //        // Не дает сохранить форму если в ней нет изменений
        //        // ModelState.AddModelError("CustomError", "Please select CV");
        //        return View();
        //    }

        //    if (!(file.ContentType == "image/jpeg" ||
        //        file.ContentType == "application/pdf"))
        //    {
        //        ModelState.AddModelError("CustomError", "Only .jpef and .pdf file allowed");
        //        return View();
        //    }
        //    if (ModelState.IsValid)
        //    {

        //        string fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
        //        file.SaveAs(Path.Combine(Server.MapPath("~/UploadedCV"), fileName));
        //        using (Model11 dc = new Model11())
        //        {
        //            db.Entry(companySet).State = EntityState.Modified;
        //            companySet.files = fileName;
        //            dc.CompanySet.Add(companySet);
        //            dc.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        // Очищает форму
        //        // ModelState.Clear();
        //        //companySet = null;
        //        //ViewBag.Message = "Successfully Done";

        //    }

        //    return View(companySet);
        //}

        // GET: CompanySets/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanySet companySet = db.CompanySet.Find(id);
            
            if (companySet == null)
            {
                return HttpNotFound();
            }
            return View(companySet);
        }

        // POST: CompanySets/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyId,Name,address,inn,numnalog,kpp,rs,Bank,ks,bic,ogrn,numgos,okved,oktmo,okato,tel,mailaddress,gendir")] CompanySet companySet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companySet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(companySet);
        }


        

        


        // GET: CompanySets/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanySet companySet = db.CompanySet.Find(id);
            if (companySet == null)
            {
                return HttpNotFound();
            }
            return View(companySet);
        }

        // POST: CompanySets/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompanySet companySet = db.CompanySet.Find(id);
            db.CompanySet.Remove(companySet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication11/Views/CompanySets/AddFiles.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>1</title>
</head>
<body>
    <div>
    ddddd
    </div>
</body>
</html>

WebApplication11/Views/CompanySets/Create.cshtml
@model WebApplication11.Models.CompanySet

@{
    ViewBag.Title = "Создать компанию заказчика";
}
@{
    ViewBag.Directory = "class = active";
}
@{
    ViewBag.DirectoryOpen = "open";
}
@*Скрипты обязательны для валидации проверки на уникальность вводимых данных*@
<script src="~/Scripts/jquery-2.1.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<h2>Создать компанию заказчика</h2>


@using (Html.BeginForm("Create", "CompanySets", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Юридическое лицо</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })        
    @* Начало блока с формами *@
        <div class="row">
            <div class="col-md-12">
                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.Name)
                        <span class="required">*</span>
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>

                @* Конец формы ввода *@
                <p><br></p>
                <h4>Реквизиты</h4>
                <hr />
                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.address)
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.inn)
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.inn, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.inn, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@ 

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.kpp) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.kpp, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.kpp, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.rs) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.rs, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.rs, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.bank) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.bank, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.bank, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.ks) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.ks, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.ks, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.bic) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.bic, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.bic, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.ogrn) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.ogrn, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.ogrn, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@
                            
                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.okved) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.okved, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.okved, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.oktmo) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.oktmo, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.oktmo, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.okato) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.okato, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.okato, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.tel) 
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.mailaddress)
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.mailaddress, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.mailaddress, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.gendir)
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.gendir, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.gendir, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.numgos)
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.numgos, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.numgos, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

                @* Начало формы ввода *@
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(model => model.numnalog)
                    </label>

                    <div class="col-md-4">
                        <div>
                            @Html.EditorFor(model => model.numnalog, new { htmlAttributes = new { @class = "form-control" } })
                            <span>@Html.ValidationMessageFor(model => model.numnalog, "", new { @class = "text-danger" })</span>
                        </div>
                    </div>
                </div>
                @* Конец формы ввода *@

            </div>
        </div>
        @* Конец блока с формами *@
        <p></p>
        @* Начало блока с кнопками *@
        <div class="col-md-5">
            <button type="submit" class="btn green">Сохранить</button>
            <input class="btn default" type="button" value="Отмена" onclick="location.href='@Url.Action("Index")'" />
        </div>
        @* Конец блока с кнопками *@
    </div>
}
@section Scripts {
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
}

WebApplication11/Views/CompanySets/Delete.cshtml
@model WebApplication11.Models.CompanySet

@{
    ViewBag.Title = "Удалить юридическое лицо";
}
@{
    ViewBag.Directory = "class = active";
}
@{
    ViewBag.DirectoryOpen = "open";
}
<h2>Удалить юридическое лицо</h2>
<div class="form-horizontal">
    <h3>Подтвердите удаление юридического лица</h3>
    <hr />
    <div class="portlet-body form">
        <form class="form-horizontal" role="form">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Name)</label>
                    <div class="col-md-4">
                        <input type="password" class="form-control" placeholder="@Html.DisplayFor(model => model.Name)" disabled>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @* Начало блока с кнопками *@
    <div class="col-md-5">
        <button type="submit" class="btn green">Удалить</button>
        <input class="btn default" type="button" value="Отмена" onclick="location.href='@Url.Action("Index")'" />
    </div>
    @* Конец блока с кнопками *@
}

WebApplication11/Views/CompanySets/Details.cshtml
@model WebApplication11.Models.CompanySet

@{
    ViewBag.Title = "Юридическое лицо";
}
@{
    ViewBag.Directory = "class = active";
}
@{
    ViewBag.DirectoryOpen = "open";
}
<h2>Юридическое лицо</h2>

<div class="form-horizontal">
    <h4>Информация</h4>
    <hr />
    <div class="portlet-body form">
        <form class="form-horizontal" role="form">
            <div class="form-body">
                <div class="portlet-body">
                    <div class="row static-info">
                        <div class="col-md-2 value">@Html.DisplayNameFor(model => model.Name):</div>
                        <div class="col-md-7 name">@Html.DisplayFor(model => model.Name)</div>
                    </div>
                    <p><br></p>
                    <h4>Реквизиты</h4>
                    <hr />
                    @if (Model.address != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.address):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.address)</div>
                        </div> 
                    }
                    @if (Model.inn != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.inn):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.inn)</div>
                        </div> 
                    }
                    @if (Model.kpp != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.kpp):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.kpp)</div>
                        </div> 
                    }
                    @if (Model.rs != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.rs):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.rs)</div>
                        </div> 
                    }
                    @if (Model.bank != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.bank):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.bank)</div>
                        </div> 
                    }
                    @if (Model.ks != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.ks):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.ks)</div>
                        </div> 
                    }
                    @if (Model.bic != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.bic):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.bic)</div>
                        </div> 
                    }
                    @if (Model.ogrn != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.ogrn):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.ogrn)</div>
                        </div> 
                    }
                    @if (Model.okved != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.okved):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.okved)</div>
                        </div> 
                    }
                    @if (Model.oktmo != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.oktmo):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.oktmo)</div>
                        </div> 
                    }
                    @if (Model.okato != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.okato):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.okato)</div>
                        </div> 
                    }
                    @if (Model.tel != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.tel):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.tel)</div>
                        </div> 
                    }
                    @if (Model.mailaddress != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.mailaddress):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.mailaddress)</div>
                        </div> 
                    }
                    @if (Model.gendir != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.gendir):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.gendir)</div>
                        </div> 
                    }
                    @if (Model.numgos != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.numgos):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.numgos)</div>
                        </div> 
                    }
                    @if (Model.numnalog != null)
                    {
                        <div class="row static-info">
                            <div class="col-md-2 value">@Html.DisplayNameFor(model => model.numnalog):</div>
                            <div class="col-md-7 name">@Html.DisplayFor(model => model.numnalog)</div>
                        </div> 
                    }
                </div>

        </form>
    </div>

</div>

@* Начало блока с кнопками *@
<div class="col-md-5">
    <input class="btn green" type="button" value="Изменить" onclick="location.href='@Url.Action("Edit", new { id = Model.CompanyId })'" />
    <input class="btn default" type="button" value="Отмена" onclick="location.href='@Url.Action("Index")'" />
</div>
@* Конец блока с кнопками *@

WebApplication11/Views/CompanySets/Index.cshtml
@model IEnumerable<WebApplication11.Models.CompanySet>

@{
    ViewBag.Title = "Юридические лица (Заказчик)";
}
@{
    ViewBag.Directory = "class = active";
}
@{
    ViewBag.DirectoryOpen = "open";
}
<div style="overflow: hidden;">
    <div style="width: 100%;">
        <div style="float: left; width: 91%; margin-top: 0px; margin-bottom: 0; "><h2>Юридические лица (Заказчик)</h2></div>
        <div style="float: left; width: 9%;"><h2><input class="btn green" type="button" value="Добавить" onclick="location.href='@Url.Action("Create")'" /></h2></div>
    </div>
</div>
<p></p>

<div class="row">
    <div class="col-md-12">

        <div class="portlet-body">
            <table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th class="hidden-xs"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td align="center" width="35" class="text-decoration: none">
                                @Html.ActionLink(" ", "Edit", new { id = item.CompanyId }, new { @class = "fa fa-pencil", title = "Изменить" })

                                @Html.ActionLink(" ", "Details", new { id = item.CompanyId }, new { @class = "fa fa-search", title = "Подробно" })

                                @Html.ActionLink(" ", "Delete", new { id = item.CompanyId }, new { @class = "fa fa-trash-o", title = "Удалить" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>